//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disco
    {
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public System.TimeSpan Duracion { get; set; }
        public int Anio { get; set; }
        public string Distribuidora { get; set; }
        public int Ventas { get; set; }
        public string Disponibilidad { get; set; }
        public Nullable<int> IdArtista { get; set; }
        public Nullable<int> IdGeneromusical { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual GeneroMusical GeneroMusical { get; set; }
    }
}
